// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebObserver.Main.Domain.Text;
using WebObserver.Main.Domain.YouTubePlaylist;
using WebObserver.Main.Infrastructure.Data;

#nullable disable

namespace WebObserver.Main.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebObserver.Main.Domain.Base.DiffBase", b =>
                {
                    b.Property<int>("FirstEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("first_entry_id");

                    b.Property<int>("SecondEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("second_entry_id");

                    b.HasKey("FirstEntryId", "SecondEntryId");

                    b.HasIndex("SecondEntryId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Base.ObservingBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cron_expression");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("discriminator");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_observings");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_observings_template_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_observings_user_id");

                    b.ToTable("observings", (string)null);

                    b.HasDiscriminator().HasValue("ObservingBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Base.ObservingEntryBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("discriminator");

                    b.Property<int>("ObservingId")
                        .HasColumnType("integer")
                        .HasColumnName("observing_id");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occured_at");

                    b.HasKey("Id")
                        .HasName("pk_observing_entries");

                    b.ToTable("observing_entries", (string)null);

                    b.HasDiscriminator().HasValue("ObservingEntryBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Base.ObservingPayload", b =>
                {
                    b.Property<int>("ObservingId")
                        .HasColumnType("integer")
                        .HasColumnName("observing_id");

                    b.HasKey("ObservingId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Base.ObservingTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("discriminator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.ToTable("templates", (string)null);

                    b.HasDiscriminator().HasValue("ObservingTemplate");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_salt");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WebObserver.Main.Domain.YouTubePlaylist.YouTubePlaylistItem", b =>
                {
                    b.Property<string>("VideoId")
                        .HasColumnType("text")
                        .HasColumnName("video_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("Position")
                        .HasColumnType("bigint")
                        .HasColumnName("position");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("VideoOwnerChannelTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("video_owner_channel_title");

                    b.HasKey("VideoId")
                        .HasName("pk_you_tube_playlist_item");

                    b.ToTable("you_tube_playlist_item", (string)null);
                });

            modelBuilder.Entity("YouTubePlaylistItemYouTubePlaylistPayload", b =>
                {
                    b.Property<string>("ItemsVideoId")
                        .HasColumnType("text")
                        .HasColumnName("items_video_id");

                    b.Property<int>("YouTubePlaylistPayloadObservingId")
                        .HasColumnType("integer")
                        .HasColumnName("you_tube_playlist_payload_observing_id");

                    b.HasKey("ItemsVideoId", "YouTubePlaylistPayloadObservingId")
                        .HasName("pk_you_tube_playlist_item_you_tube_playlist_payload");

                    b.HasIndex("YouTubePlaylistPayloadObservingId")
                        .HasDatabaseName("ix_you_tube_playlist_item_you_tube_playlist_payload_you_tube_p");

                    b.ToTable("you_tube_playlist_item_you_tube_playlist_payload", (string)null);
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Base.Diff<WebObserver.Main.Domain.Text.TextDiffPayload>", b =>
                {
                    b.HasBaseType("WebObserver.Main.Domain.Base.DiffBase");

                    b.Property<TextDiffPayload>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.ToTable("diff_text_diff_payload", (string)null);
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Base.Diff<WebObserver.Main.Domain.YouTubePlaylist.YouTubePlaylistDiffPayload>", b =>
                {
                    b.HasBaseType("WebObserver.Main.Domain.Base.DiffBase");

                    b.Property<YouTubePlaylistDiffPayload>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.ToTable("diff_you_tube_playlist_diff_payload", (string)null);
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Text.TextObserving", b =>
                {
                    b.HasBaseType("WebObserver.Main.Domain.Base.ObservingBase");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.ToTable("observings", (string)null);

                    b.HasDiscriminator().HasValue("TextObserving");
                });

            modelBuilder.Entity("WebObserver.Main.Domain.YouTubePlaylist.YouTubePlaylistObserving", b =>
                {
                    b.HasBaseType("WebObserver.Main.Domain.Base.ObservingBase");

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("playlist_id");

                    b.ToTable("observings", (string)null);

                    b.HasDiscriminator().HasValue("YouTubePlaylistObserving");
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Base.ObservingEntry<WebObserver.Main.Domain.Text.TextPayload>", b =>
                {
                    b.HasBaseType("WebObserver.Main.Domain.Base.ObservingEntryBase");

                    b.Property<int?>("LastDiffFirstEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("last_diff_first_entry_id");

                    b.Property<int?>("LastDiffSecondEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("last_diff_second_entry_id");

                    b.Property<int?>("PayloadObservingId")
                        .HasColumnType("integer")
                        .HasColumnName("payload_observing_id");

                    b.HasIndex("ObservingId")
                        .HasDatabaseName("ix_observing_entries_observing_id");

                    b.HasIndex("PayloadObservingId")
                        .HasDatabaseName("ix_observing_entries_payload_observing_id1");

                    b.HasIndex("LastDiffFirstEntryId", "LastDiffSecondEntryId")
                        .HasDatabaseName("ix_observing_entries_last_diff_first_entry_id_last_diff_second1");

                    b.ToTable("observing_entries", null, t =>
                        {
                            t.Property("LastDiffFirstEntryId")
                                .HasColumnName("observing_entry_last_diff_first_entry_id");

                            t.Property("LastDiffSecondEntryId")
                                .HasColumnName("observing_entry_last_diff_second_entry_id");

                            t.Property("PayloadObservingId")
                                .HasColumnName("observing_entry_payload_observing_id");
                        });

                    b.HasDiscriminator().HasValue("ObservingEntry<TextPayload>");
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Base.ObservingEntry<WebObserver.Main.Domain.YouTubePlaylist.YouTubePlaylistPayload>", b =>
                {
                    b.HasBaseType("WebObserver.Main.Domain.Base.ObservingEntryBase");

                    b.Property<int?>("LastDiffFirstEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("last_diff_first_entry_id");

                    b.Property<int?>("LastDiffSecondEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("last_diff_second_entry_id");

                    b.Property<int?>("PayloadObservingId")
                        .HasColumnType("integer")
                        .HasColumnName("payload_observing_id");

                    b.HasIndex("ObservingId")
                        .HasDatabaseName("ix_observing_entries_observing_id");

                    b.HasIndex("PayloadObservingId")
                        .HasDatabaseName("ix_observing_entries_payload_observing_id");

                    b.HasIndex("LastDiffFirstEntryId", "LastDiffSecondEntryId")
                        .HasDatabaseName("ix_observing_entries_last_diff_first_entry_id_last_diff_second");

                    b.ToTable("observing_entries", (string)null);

                    b.HasDiscriminator().HasValue("ObservingEntry<YouTubePlaylistPayload>");
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Text.TextPayload", b =>
                {
                    b.HasBaseType("WebObserver.Main.Domain.Base.ObservingPayload");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.ToTable("text_payload", (string)null);
                });

            modelBuilder.Entity("WebObserver.Main.Domain.YouTubePlaylist.YouTubePlaylistPayload", b =>
                {
                    b.HasBaseType("WebObserver.Main.Domain.Base.ObservingPayload");

                    b.ToTable("you_tube_playlist_payload", (string)null);
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Text.TextObservingTemplate", b =>
                {
                    b.HasBaseType("WebObserver.Main.Domain.Base.ObservingTemplate");

                    b.ToTable("templates", (string)null);

                    b.HasDiscriminator().HasValue("TextObservingTemplate");
                });

            modelBuilder.Entity("WebObserver.Main.Domain.YouTubePlaylist.YouTubePlaylistObservingTemplate", b =>
                {
                    b.HasBaseType("WebObserver.Main.Domain.Base.ObservingTemplate");

                    b.ToTable("templates", (string)null);

                    b.HasDiscriminator().HasValue("YouTubePlaylistObservingTemplate");
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Text.TextObservingEntry", b =>
                {
                    b.HasBaseType("WebObserver.Main.Domain.Base.ObservingEntry<WebObserver.Main.Domain.Text.TextPayload>");

                    b.ToTable("observing_entries", null, t =>
                        {
                            t.Property("LastDiffFirstEntryId")
                                .HasColumnName("observing_entry_last_diff_first_entry_id");

                            t.Property("LastDiffSecondEntryId")
                                .HasColumnName("observing_entry_last_diff_second_entry_id");

                            t.Property("PayloadObservingId")
                                .HasColumnName("observing_entry_payload_observing_id");
                        });

                    b.HasDiscriminator().HasValue("TextObservingEntry");
                });

            modelBuilder.Entity("WebObserver.Main.Domain.YouTubePlaylist.YouTubePlaylistObservingEntry", b =>
                {
                    b.HasBaseType("WebObserver.Main.Domain.Base.ObservingEntry<WebObserver.Main.Domain.YouTubePlaylist.YouTubePlaylistPayload>");

                    b.ToTable("observing_entries", (string)null);

                    b.HasDiscriminator().HasValue("YouTubePlaylistObservingEntry");
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Base.DiffBase", b =>
                {
                    b.HasOne("WebObserver.Main.Domain.Base.ObservingEntryBase", null)
                        .WithMany()
                        .HasForeignKey("FirstEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebObserver.Main.Domain.Base.ObservingEntryBase", null)
                        .WithMany()
                        .HasForeignKey("SecondEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Base.ObservingBase", b =>
                {
                    b.HasOne("WebObserver.Main.Domain.Base.ObservingTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_observings_templates_template_id");

                    b.HasOne("WebObserver.Main.Domain.Entities.User", null)
                        .WithMany("Observings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_observings_users_user_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Base.ObservingPayload", b =>
                {
                    b.HasOne("WebObserver.Main.Domain.Base.ObservingEntryBase", null)
                        .WithOne()
                        .HasForeignKey("WebObserver.Main.Domain.Base.ObservingPayload", "ObservingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YouTubePlaylistItemYouTubePlaylistPayload", b =>
                {
                    b.HasOne("WebObserver.Main.Domain.YouTubePlaylist.YouTubePlaylistItem", null)
                        .WithMany()
                        .HasForeignKey("ItemsVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_you_tube_playlist_item_you_tube_playlist_payload_you_tube_p");

                    b.HasOne("WebObserver.Main.Domain.YouTubePlaylist.YouTubePlaylistPayload", null)
                        .WithMany()
                        .HasForeignKey("YouTubePlaylistPayloadObservingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_you_tube_playlist_item_you_tube_playlist_payload_you_tube_p1");
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Base.ObservingEntry<WebObserver.Main.Domain.Text.TextPayload>", b =>
                {
                    b.HasOne("WebObserver.Main.Domain.Text.TextObserving", null)
                        .WithMany("Entries")
                        .HasForeignKey("ObservingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_observing_entries_observings_observing_id");

                    b.HasOne("WebObserver.Main.Domain.Text.TextPayload", "Payload")
                        .WithMany()
                        .HasForeignKey("PayloadObservingId")
                        .HasConstraintName("fk_observing_entries_text_payload_payload_observing_id");

                    b.HasOne("WebObserver.Main.Domain.Base.DiffBase", "LastDiff")
                        .WithMany()
                        .HasForeignKey("LastDiffFirstEntryId", "LastDiffSecondEntryId");

                    b.Navigation("LastDiff");

                    b.Navigation("Payload");
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Base.ObservingEntry<WebObserver.Main.Domain.YouTubePlaylist.YouTubePlaylistPayload>", b =>
                {
                    b.HasOne("WebObserver.Main.Domain.YouTubePlaylist.YouTubePlaylistObserving", null)
                        .WithMany("Entries")
                        .HasForeignKey("ObservingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_observing_entries_observings_observing_id");

                    b.HasOne("WebObserver.Main.Domain.YouTubePlaylist.YouTubePlaylistPayload", "Payload")
                        .WithMany()
                        .HasForeignKey("PayloadObservingId")
                        .HasConstraintName("fk_observing_entries_you_tube_playlist_payload_payload_observi");

                    b.HasOne("WebObserver.Main.Domain.Base.DiffBase", "LastDiff")
                        .WithMany()
                        .HasForeignKey("LastDiffFirstEntryId", "LastDiffSecondEntryId");

                    b.Navigation("LastDiff");

                    b.Navigation("Payload");
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Entities.User", b =>
                {
                    b.Navigation("Observings");
                });

            modelBuilder.Entity("WebObserver.Main.Domain.Text.TextObserving", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("WebObserver.Main.Domain.YouTubePlaylist.YouTubePlaylistObserving", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
